/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    testimonials: Testimonial;
    faqs: Faq;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'gallery-page': GalleryPage;
    'privacy-policy': PrivacyPolicy;
    'terms-and-conditions': TermsAndCondition;
    'cookie-policy': CookiePolicy;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'gallery-page': GalleryPageSelect<false> | GalleryPageSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'terms-and-conditions': TermsAndConditionsSelect<false> | TermsAndConditionsSelect<true>;
    'cookie-policy': CookiePolicySelect<false> | CookiePolicySelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Create the homepage service card and the complete service detail page from one clearly organised form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Example: Boiler Servicing. This is also the record name in the admin panel.
   */
  title: string;
  /**
   * Example: boiler-servicing creates /services/boiler-servicing.
   */
  slug: string;
  /**
   * Short service name used in forms and navigation.
   */
  label: string;
  homepageCard: {
    title: string;
    description: string;
    /**
     * Upload the image shown on this service's homepage card.
     */
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    /**
     * Example: Same-day available. Leave empty to hide it.
     */
    badge?: string | null;
  };
  eyebrow?: string | null;
  headline: string;
  highlight?: string | null;
  ending?: string | null;
  description: string;
  /**
   * Upload the large image displayed beside the service heading.
   */
  heroImage?: (number | null) | Media;
  ctaLabel?: string | null;
  /**
   * Optional pricing rows displayed over the hero image.
   */
  options?:
    | {
        name: string;
        price: string;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  reassurance?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  includesHeader: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  includedItems?:
    | {
        number: string;
        title: string;
        description: string;
        /**
         * Upload the image displayed at the top of this card.
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  solutionsHeader: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  specifications?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  processHeader: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  processSteps?:
    | {
        number: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  ctaHeader: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  ctaReassurance?: string | null;
  /**
   * Add a button label and destination, then choose its visual style and link behaviour.
   */
  ctas?:
    | {
        label: string;
        /**
         * Optional. Without an href, the CTA renders as a button.
         */
        href?: string | null;
        btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
        target?: ('_self' | '_blank' | '_parent' | '_top') | null;
        /**
         * Optional link relationship, for example: noopener noreferrer.
         */
        rel?: string | null;
        theme?: ('LIGHT' | 'DARK') | null;
        id?: string | null;
      }[]
    | null;
  faqHeader: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  faqs?: (number | Faq)[] | null;
  /**
   * Leave the heading empty to use the default from Site settings. Select testimonials to override the default list for this page.
   */
  testimonialsSection?: {
    title?: string | null;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
    testimonials?: (number | Testimonial)[] | null;
  };
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload an image and provide accessible alternative text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Briefly describe the image for accessibility and search engines.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  page:
    | 'general'
    | 'homepage'
    | 'about'
    | 'boiler-servicing'
    | 'boiler-breakdown-repairs'
    | 'boiler-installation'
    | 'underfloor-heating'
    | 'powerflushing'
    | 'central-heating';
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  quote: string;
  rating: number;
  /**
   * Optional customer role, location or service name.
   */
  designation?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  label?: T;
  homepageCard?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        ctaLabel?: T;
        badge?: T;
      };
  eyebrow?: T;
  headline?: T;
  highlight?: T;
  ending?: T;
  description?: T;
  heroImage?: T;
  ctaLabel?: T;
  options?:
    | T
    | {
        name?: T;
        price?: T;
        id?: T;
      };
  note?: T;
  reassurance?:
    | T
    | {
        text?: T;
        id?: T;
      };
  includesHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  includedItems?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  solutionsHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  specifications?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  processHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  processSteps?:
    | T
    | {
        number?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  ctaReassurance?: T;
  ctas?:
    | T
    | {
        label?: T;
        href?: T;
        btnStyle?: T;
        target?: T;
        rel?: T;
        theme?: T;
        id?: T;
      };
  faqHeader?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  faqs?: T;
  testimonialsSection?:
    | T
    | {
        title?: T;
        highlight?: T;
        description?: T;
        testimonials?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  rating?: T;
  designation?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  page?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  hero: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    /**
     * Add a button label and destination, then choose its visual style and link behaviour.
     */
    ctas?:
      | {
          label: string;
          /**
           * Optional. Without an href, the CTA renders as a button.
           */
          href?: string | null;
          btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          /**
           * Optional link relationship, for example: noopener noreferrer.
           */
          rel?: string | null;
          theme?: ('LIGHT' | 'DARK') | null;
          id?: string | null;
        }[]
      | null;
    reassurance?: string | null;
    /**
     * Optional hero image. The existing website image is used when this is empty.
     */
    image?: (number | null) | Media;
    statsCard?: {
      enabled?: boolean | null;
      value?: string | null;
      label?: string | null;
      description?: string | null;
    };
    iconCard?: {
      enabled?: boolean | null;
      title?: string | null;
      description?: string | null;
      icon?: ('shield' | 'sparkles' | 'calendar' | 'check' | 'map-pin' | 'clock' | 'phone' | 'wrench') | null;
    };
    /**
     * Information cards displayed below the homepage hero. Choose an icon by name.
     */
    infoItems?:
      | {
          title: string;
          description: string;
          icon: 'shield' | 'sparkles' | 'calendar' | 'check' | 'map-pin' | 'clock' | 'phone' | 'wrench';
          id?: string | null;
        }[]
      | null;
  };
  experience: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    /**
     * Choose existing brand logos or upload new images. Use SVG logos where possible for sharper results and better performance.
     */
    brandLogos?: (number | Media)[] | null;
    calloutTitle?: string | null;
    calloutDescription?: string | null;
  };
  about: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      /**
       * Use separate paragraphs to add spacing between blocks of text.
       */
      description?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
    /**
     * Choose an existing image or upload a new image for the homepage About section.
     */
    image?: (number | null) | Media;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    badgeTitle?: string | null;
    badgeDescription?: string | null;
    reassurance?: string | null;
    /**
     * Add a button label and destination, then choose its visual style and link behaviour.
     */
    ctas?:
      | {
          label: string;
          /**
           * Optional. Without an href, the CTA renders as a button.
           */
          href?: string | null;
          btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          /**
           * Optional link relationship, for example: noopener noreferrer.
           */
          rel?: string | null;
          theme?: ('LIGHT' | 'DARK') | null;
          id?: string | null;
        }[]
      | null;
  };
  servicesSection: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    services?: (number | Service)[] | null;
  };
  boilerOptions: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    items?:
      | {
          title: string;
          /**
           * Highlighted italic text displayed directly below the boiler title.
           */
          highlight?: string | null;
          description: string;
          /**
           * Text displayed after the “Best for:” label.
           */
          note?: string | null;
          /**
           * Add the features displayed with check marks on this boiler card.
           */
          bulletPoints?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Choose an existing image or upload a new image for this boiler card. The current default image is used when this is empty.
           */
          image?: (number | null) | Media;
          ctaLabel?: string | null;
          /**
           * Show the Popular choice badge on this boiler card.
           */
          popularChoice?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  callToAction: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    reassurance?: string | null;
    /**
     * Add a button label and destination, then choose its visual style and link behaviour.
     */
    ctas?:
      | {
          label: string;
          /**
           * Optional. Without an href, the CTA renders as a button.
           */
          href?: string | null;
          btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          /**
           * Optional link relationship, for example: noopener noreferrer.
           */
          rel?: string | null;
          theme?: ('LIGHT' | 'DARK') | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Leave the heading empty to use the default from Site settings. Select testimonials to override the default list for this page.
   */
  testimonialsSection?: {
    title?: string | null;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
    testimonials?: (number | Testimonial)[] | null;
  };
  whyChooseUs: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    items?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  faqSection: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    faqs?: (number | Faq)[] | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  hero: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    image?: (number | null) | Media;
    features?:
      | {
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    badgeTitle?: string | null;
    badgeDescription?: string | null;
    reassurance?: string | null;
    /**
     * Add a button label and destination, then choose its visual style and link behaviour.
     */
    ctas?:
      | {
          label: string;
          /**
           * Optional. Without an href, the CTA renders as a button.
           */
          href?: string | null;
          btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          /**
           * Optional link relationship, for example: noopener noreferrer.
           */
          rel?: string | null;
          theme?: ('LIGHT' | 'DARK') | null;
          id?: string | null;
        }[]
      | null;
  };
  principles: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    image?: (number | null) | Media;
    badgeTitle?: string | null;
    badgeDescription?: string | null;
    items?:
      | {
          number: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Heading for the boiler-brand callout.
     */
    calloutTitle?: string | null;
    /**
     * Description for the boiler-brand callout.
     */
    calloutDescription?: string | null;
  };
  experience: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    /**
     * Choose existing brand logos or upload new images. Use SVG logos where possible for sharper results and better performance.
     */
    brandLogos?: (number | Media)[] | null;
  };
  servicesSection: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    services?: (number | Service)[] | null;
  };
  faqSection: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    faqs?: (number | Faq)[] | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  hero: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    /**
     * Add a button label and destination, then choose its visual style and link behaviour.
     */
    ctas?:
      | {
          label: string;
          /**
           * Optional. Without an href, the CTA renders as a button.
           */
          href?: string | null;
          btnStyle: 'CTA_PRIMARY' | 'CTA_SECONDARY';
          target?: ('_self' | '_blank' | '_parent' | '_top') | null;
          /**
           * Optional link relationship, for example: noopener noreferrer.
           */
          rel?: string | null;
          theme?: ('LIGHT' | 'DARK') | null;
          id?: string | null;
        }[]
      | null;
  };
  contactSection: {
    header: {
      eyebrow?: string | null;
      title: string;
      /**
       * Optional words displayed with the brand style.
       */
      highlight?: string | null;
      description?: string | null;
    };
    email?: string | null;
    phone?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page".
 */
export interface GalleryPage {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  header: {
    eyebrow?: string | null;
    title: string;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
  };
  /**
   * Leave the heading empty to use the default from Site settings. Select testimonials to override the default list for this page.
   */
  testimonialsSection?: {
    title?: string | null;
    /**
     * Optional words displayed with the brand style.
     */
    highlight?: string | null;
    description?: string | null;
    testimonials?: (number | Testimonial)[] | null;
  };
  /**
   * Select images in the order they should appear on the Gallery page.
   */
  items?: (number | Media)[] | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  title: string;
  description?: string | null;
  /**
   * Use this editor for headings, paragraphs, lists and links.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  title: string;
  description?: string | null;
  /**
   * Use this editor for headings, paragraphs, lists and links.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy".
 */
export interface CookiePolicy {
  id: number;
  seo: {
    title: string;
    description: string;
    canonicalPath?: string | null;
    noIndex?: boolean | null;
  };
  title: string;
  description?: string | null;
  /**
   * Use this editor for headings, paragraphs, lists and links.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  email: string;
  /**
   * Used as both the displayed phone number and the clickable call link.
   */
  phone: string;
  address?: string | null;
  serviceArea?: string | null;
  companyNumber?: string | null;
  gasSafeNumber?: string | null;
  testimonialDefaults: {
    title: string;
    highlight?: string | null;
    description: string;
  };
  navigation?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        /**
         * Optional links shown in a dropdown when visitors hover over this navigation item.
         */
        children?:
          | {
              label: string;
              href: string;
              openInNewTab?: boolean | null;
              /**
               * Optional second-level links shown beside this sub-navigation item.
               */
              nestedChildren?:
                | {
                    label: string;
                    href: string;
                    openInNewTab?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  hero?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              btnStyle?: T;
              target?: T;
              rel?: T;
              theme?: T;
              id?: T;
            };
        reassurance?: T;
        image?: T;
        statsCard?:
          | T
          | {
              enabled?: T;
              value?: T;
              label?: T;
              description?: T;
            };
        iconCard?:
          | T
          | {
              enabled?: T;
              title?: T;
              description?: T;
              icon?: T;
            };
        infoItems?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  experience?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        brandLogos?: T;
        calloutTitle?: T;
        calloutDescription?: T;
      };
  about?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        image?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        badgeTitle?: T;
        badgeDescription?: T;
        reassurance?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              btnStyle?: T;
              target?: T;
              rel?: T;
              theme?: T;
              id?: T;
            };
      };
  servicesSection?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        services?: T;
      };
  boilerOptions?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        items?:
          | T
          | {
              title?: T;
              highlight?: T;
              description?: T;
              note?: T;
              bulletPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              ctaLabel?: T;
              popularChoice?: T;
              id?: T;
            };
      };
  callToAction?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        reassurance?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              btnStyle?: T;
              target?: T;
              rel?: T;
              theme?: T;
              id?: T;
            };
      };
  testimonialsSection?:
    | T
    | {
        title?: T;
        highlight?: T;
        description?: T;
        testimonials?: T;
      };
  whyChooseUs?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  faqSection?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        faqs?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  hero?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        image?: T;
        features?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        badgeTitle?: T;
        badgeDescription?: T;
        reassurance?: T;
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              btnStyle?: T;
              target?: T;
              rel?: T;
              theme?: T;
              id?: T;
            };
      };
  principles?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        image?: T;
        badgeTitle?: T;
        badgeDescription?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        calloutTitle?: T;
        calloutDescription?: T;
      };
  experience?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        brandLogos?: T;
      };
  servicesSection?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        services?: T;
      };
  faqSection?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        faqs?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  hero?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        ctas?:
          | T
          | {
              label?: T;
              href?: T;
              btnStyle?: T;
              target?: T;
              rel?: T;
              theme?: T;
              id?: T;
            };
      };
  contactSection?:
    | T
    | {
        header?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              highlight?: T;
              description?: T;
            };
        email?: T;
        phone?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-page_select".
 */
export interface GalleryPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  header?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        highlight?: T;
        description?: T;
      };
  testimonialsSection?:
    | T
    | {
        title?: T;
        highlight?: T;
        description?: T;
        testimonials?: T;
      };
  items?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  title?: T;
  description?: T;
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  title?: T;
  description?: T;
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalPath?: T;
        noIndex?: T;
      };
  title?: T;
  description?: T;
  content?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  email?: T;
  phone?: T;
  address?: T;
  serviceArea?: T;
  companyNumber?: T;
  gasSafeNumber?: T;
  testimonialDefaults?:
    | T
    | {
        title?: T;
        highlight?: T;
        description?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
              nestedChildren?:
                | T
                | {
                    label?: T;
                    href?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}